---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  nodes_path: nodes

platforms:
  - name: centos65
    driver:
      box: box-cutter/centos65
      box_url: box-cutter/centos65

suites:
  - name: default
    run_list:
      - recipe[test-search::default]
    attributes:
